<a href="https://colab.research.google.com/github/wilsonh22/435Assn1/blob/main/Wilson_H_Discrete_Fourier_Transform_(DFT).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import cmath
import math

In [ ]:
def dft_from_scratch(x):
    """
    Computes the 1D Discrete Fourier Transform (DFT) of a sequence.

    Args:
        x (np.ndarray): A numpy array of numerical values representing the input signal.

    Returns:
        np.ndarray: A numpy array of complex numbers representing the DFT of the input signal.
    """
    N = len(x)
    X = np.zeros(N, dtype=np.complex128)
    for k in range(N):
        sum_val = 0.0
        for n in range(N):
            angle = -2 * math.pi * k * n / N
            sum_val += x[n] * cmath.exp(1j * angle)
        X[k] = sum_val
    return X

In [ ]:
def idft_from_scratch(X):
    """
    Computes the 1D Inverse Discrete Fourier Transform (IDFT) of a sequence.

    Args:
        X (np.ndarray): A numpy array of complex numbers representing the transformed signal.

    Returns:
        np.ndarray: A numpy array of complex numbers (which should be real-valued)
                    representing the reconstructed signal.
    """
    N = len(X)
    x = np.zeros(N, dtype=np.complex128)
    for n in range(N):
        sum_val = 0.0
        for k in range(N):
            angle = 2 * math.pi * k * n / N
            sum_val += X[k] * cmath.exp(1j * angle)
        x[n] = sum_val / N
    return x

In [ ]:
def twoD_dft_from_scratch(X):
  """
  Computes the 2D Inverse Discrete Fourier Transform (IDFT) of a sequence.

  Args:
      X (np.ndarray): A numpy array of numbers representing the input signal. (16*16)

  Returns:
      np.ndarray: A numpy array of complex numbers representing the 2dft of the input signal.
  """
  #row column
  row, column = np.shape(X)

  #initial mask for fft for rowa
  initial = np.zeros((row, column), dtype=np.complex128)

  #calculate row using 1d fft
  for i in range(row):
    initial[i, :] = dft_from_scratch(X[i, :])

  #initialize 2nd frequency mask for column
  final = np.zeros((row, column), dtype=np.complex128)

  #calculate column sing 1d fft
  for j in range(column):
      final[:, j] = dft_from_scratch(initial[:, j])

  return final

In [ ]:
#(16x16 with 7x7 block of ones in center)
X = np.array([
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
], dtype=np.float64)

print("Original 16x16 Input Matrix:")
print(X)
print("-" * 50)


dft_result = twoD_dft_from_scratch(X)

print("2D DFT (magnitude spectrum):")
print(np.round(np.abs(dft_result), 2))
print("-" * 50)

transformed_matrix = twoD_dft_from_scratch(X)
transformed_vector = transformed_matrix.flatten()

for i, val in enumerate(transformed_vector):
  magnitude = np.abs(val)
  phase = np.angle(val)
  print(f"  Bin {i}: Magnitude = {magnitude:.2f}, Phase = {phase:.2f} rad")


Original 16x16 Input Matrix:
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
--------------------------------------------------
2D DFT (magnitude spectrum):
[[56.   40.22  8.   11.97  8.    5.35  8.    1.59  8.    1.59  8.    5.35


In [ ]:
#(16x16 with 7x7 block of ones in center)
X = np.array([
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,1,1,1,1,1,1,1,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
], dtype=np.float64)

fft_result = np.fft.fft2(X)
fft_result_flattened = fft_result.flatten()

for i, val in enumerate(transformed_vector):
  magnitude = np.abs(val)
  phase = np.angle(val)
  print(f"  Bin {i}: Magnitude = {magnitude:.2f}, Phase = {phase:.2f} rad")

  Bin 0: Magnitude = 56.00, Phase = 0.00 rad
  Bin 1: Magnitude = 40.22, Phase = -2.75 rad
  Bin 2: Magnitude = 8.00, Phase = 0.79 rad
  Bin 3: Magnitude = 11.97, Phase = 1.18 rad
  Bin 4: Magnitude = 8.00, Phase = -1.57 rad
  Bin 5: Magnitude = 5.35, Phase = -1.18 rad
  Bin 6: Magnitude = 8.00, Phase = 2.36 rad
  Bin 7: Magnitude = 1.59, Phase = 2.75 rad
  Bin 8: Magnitude = 8.00, Phase = 0.00 rad
  Bin 9: Magnitude = 1.59, Phase = -2.75 rad
  Bin 10: Magnitude = 8.00, Phase = -2.36 rad
  Bin 11: Magnitude = 5.35, Phase = 1.18 rad
  Bin 12: Magnitude = 8.00, Phase = 1.57 rad
  Bin 13: Magnitude = 11.97, Phase = -1.18 rad
  Bin 14: Magnitude = 8.00, Phase = -0.79 rad
  Bin 15: Magnitude = 40.22, Phase = 2.75 rad
  Bin 16: Magnitude = 35.88, Phase = -2.55 rad
  Bin 17: Magnitude = 25.77, Phase = 0.98 rad
  Bin 18: Magnitude = 5.13, Phase = -1.77 rad
  Bin 19: Magnitude = 7.67, Phase = -1.37 rad
  Bin 20: Magnitude = 5.13, Phase = 2.16 rad
  Bin 21: Magnitude = 3.42, Phase = 2.55 rad
  B

In [ ]:
# Example usage with a vector of length 16
N = 16
# Create a sample input vector as a numpy array
# This is a sine wave with a frequency of 2 cycles over the vector length
input_vector = np.array([np.sin(2 * np.pi * 2 * i / N) for i in range(N)])

print(f"Original Vector (length {N}):")
print(np.round(input_vector, 2))
print("-" * 30)

# Perform the DFT using the from-scratch function
transformed_vector = dft_from_scratch(input_vector)
print("Transformed Vector (DFT):")
# Print the magnitude and phase of each complex number
for i, val in enumerate(transformed_vector):
    magnitude = np.abs(val)
    phase = np.angle(val)
    print(f"  Bin {i}: Magnitude = {magnitude:.2f}, Phase = {phase:.2f} rad")
print("-" * 30)

# Perform the IDFT to reconstruct the original signal
reconstructed_vector = idft_from_scratch(transformed_vector)
print("Reconstructed Vector (IDFT):")
# Print the real part of the reconstructed complex numbers
print(np.round(reconstructed_vector.real, 2))
print("-" * 30)

# Verify that the reconstruction is close to the original using numpy.allclose
print("Verification:")
is_close = np.allclose(reconstructed_vector.real, input_vector)
print(f"Is reconstructed vector close to original? {is_close}")

NameError: name 'np' is not defined